# Generated by Django 5.1.2 on 2024-10-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppName', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
